<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>40ff1a5f-efe3-477a-8291-2105f02b800f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Broot.Redirect.Core\Broot.Redirect.Core.csproj" />
    <ProjectReference Include="..\Broot.Redirect.Infrastructure\Broot.Redirect.Infrastructure.csproj" />
  </ItemGroup>

</Project>
